package com.expleoautomation.dao;

import java.util.Date;

public class TDED_SUSPECT_REPORTS {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TDED_SUSPECT_REPORTS.SR_ID
     *
     * @mbg.generated Tue Dec 15 16:02:14 GMT 2020
     */
    private Short SR_ID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TDED_SUSPECT_REPORTS.SR_CASE_ID
     *
     * @mbg.generated Tue Dec 15 16:02:14 GMT 2020
     */
    private Short SR_CASE_ID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TDED_SUSPECT_REPORTS.SR_STATUS
     *
     * @mbg.generated Tue Dec 15 16:02:14 GMT 2020
     */
    private Short SR_STATUS;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TDED_SUSPECT_REPORTS.SR_DATE_OF_CREATION
     *
     * @mbg.generated Tue Dec 15 16:02:14 GMT 2020
     */
    private Date SR_DATE_OF_CREATION;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TDED_SUSPECT_REPORTS.SR_DATE_OF_COMPLETION
     *
     * @mbg.generated Tue Dec 15 16:02:14 GMT 2020
     */
    private Date SR_DATE_OF_COMPLETION;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TDED_SUSPECT_REPORTS.SR_OUT_OF_HOURS_FLAG
     *
     * @mbg.generated Tue Dec 15 16:02:14 GMT 2020
     */
    private String SR_OUT_OF_HOURS_FLAG;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TDED_SUSPECT_REPORTS.SR_NDCC_LDCC_NOTIFIED_NAME
     *
     * @mbg.generated Tue Dec 15 16:02:14 GMT 2020
     */
    private String SR_NDCC_LDCC_NOTIFIED_NAME;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TDED_SUSPECT_REPORTS.SR_CVRL_RVL_NOTIFIED_NAME
     *
     * @mbg.generated Tue Dec 15 16:02:14 GMT 2020
     */
    private String SR_CVRL_RVL_NOTIFIED_NAME;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TDED_SUSPECT_REPORTS.SR_REGIONAL_SSVI_NOTIFIED_NAME
     *
     * @mbg.generated Tue Dec 15 16:02:14 GMT 2020
     */
    private String SR_REGIONAL_SSVI_NOTIFIED_NAME;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TDED_SUSPECT_REPORTS.SR_REGIONAL_SVI_NOTIFIED_NAME
     *
     * @mbg.generated Tue Dec 15 16:02:14 GMT 2020
     */
    private String SR_REGIONAL_SVI_NOTIFIED_NAME;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TDED_SUSPECT_REPORTS.SR_VPHIS_SVI_NOTIFIED_NAME
     *
     * @mbg.generated Tue Dec 15 16:02:14 GMT 2020
     */
    private String SR_VPHIS_SVI_NOTIFIED_NAME;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TDED_SUSPECT_REPORTS.SR_AUDIT_USER
     *
     * @mbg.generated Tue Dec 15 16:02:14 GMT 2020
     */
    private String SR_AUDIT_USER;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TDED_SUSPECT_REPORTS.SR_AUDIT_DATE
     *
     * @mbg.generated Tue Dec 15 16:02:14 GMT 2020
     */
    private Date SR_AUDIT_DATE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TDED_SUSPECT_REPORTS.SR_AUDIT_ACTION
     *
     * @mbg.generated Tue Dec 15 16:02:14 GMT 2020
     */
    private String SR_AUDIT_ACTION;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TDED_SUSPECT_REPORTS.SR_VER_NUM
     *
     * @mbg.generated Tue Dec 15 16:02:14 GMT 2020
     */
    private Short SR_VER_NUM;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TDED_SUSPECT_REPORTS.SR_AUDIT_CREATE_USER
     *
     * @mbg.generated Tue Dec 15 16:02:14 GMT 2020
     */
    private String SR_AUDIT_CREATE_USER;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TDED_SUSPECT_REPORTS.SR_AUDIT_CREATE_DATE
     *
     * @mbg.generated Tue Dec 15 16:02:14 GMT 2020
     */
    private Date SR_AUDIT_CREATE_DATE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TDED_SUSPECT_REPORTS.SR_AUDIT_LOCATION
     *
     * @mbg.generated Tue Dec 15 16:02:14 GMT 2020
     */
    private String SR_AUDIT_LOCATION;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TDED_SUSPECT_REPORTS.SR_PREM_ID
     *
     * @mbg.generated Tue Dec 15 16:02:14 GMT 2020
     */
    private Short SR_PREM_ID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TDED_SUSPECT_REPORTS.SR_JPA_UPDATED_BY
     *
     * @mbg.generated Tue Dec 15 16:02:14 GMT 2020
     */
    private String SR_JPA_UPDATED_BY;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TDED_SUSPECT_REPORTS.SR_JPA_UPDATED_DATE
     *
     * @mbg.generated Tue Dec 15 16:02:14 GMT 2020
     */
    private Date SR_JPA_UPDATED_DATE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TDED_SUSPECT_REPORTS.SR_JPA_VERSION
     *
     * @mbg.generated Tue Dec 15 16:02:14 GMT 2020
     */
    private Short SR_JPA_VERSION;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TDED_SUSPECT_REPORTS.SR_ID
     *
     * @return the value of TDED_SUSPECT_REPORTS.SR_ID
     *
     * @mbg.generated Tue Dec 15 16:02:14 GMT 2020
     */
    public Short getSR_ID() {
        return SR_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TDED_SUSPECT_REPORTS.SR_ID
     *
     * @param SR_ID the value for TDED_SUSPECT_REPORTS.SR_ID
     *
     * @mbg.generated Tue Dec 15 16:02:14 GMT 2020
     */
    public void setSR_ID(Short SR_ID) {
        this.SR_ID = SR_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TDED_SUSPECT_REPORTS.SR_CASE_ID
     *
     * @return the value of TDED_SUSPECT_REPORTS.SR_CASE_ID
     *
     * @mbg.generated Tue Dec 15 16:02:14 GMT 2020
     */
    public Short getSR_CASE_ID() {
        return SR_CASE_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TDED_SUSPECT_REPORTS.SR_CASE_ID
     *
     * @param SR_CASE_ID the value for TDED_SUSPECT_REPORTS.SR_CASE_ID
     *
     * @mbg.generated Tue Dec 15 16:02:14 GMT 2020
     */
    public void setSR_CASE_ID(Short SR_CASE_ID) {
        this.SR_CASE_ID = SR_CASE_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TDED_SUSPECT_REPORTS.SR_STATUS
     *
     * @return the value of TDED_SUSPECT_REPORTS.SR_STATUS
     *
     * @mbg.generated Tue Dec 15 16:02:14 GMT 2020
     */
    public Short getSR_STATUS() {
        return SR_STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TDED_SUSPECT_REPORTS.SR_STATUS
     *
     * @param SR_STATUS the value for TDED_SUSPECT_REPORTS.SR_STATUS
     *
     * @mbg.generated Tue Dec 15 16:02:14 GMT 2020
     */
    public void setSR_STATUS(Short SR_STATUS) {
        this.SR_STATUS = SR_STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TDED_SUSPECT_REPORTS.SR_DATE_OF_CREATION
     *
     * @return the value of TDED_SUSPECT_REPORTS.SR_DATE_OF_CREATION
     *
     * @mbg.generated Tue Dec 15 16:02:14 GMT 2020
     */
    public Date getSR_DATE_OF_CREATION() {
        return SR_DATE_OF_CREATION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TDED_SUSPECT_REPORTS.SR_DATE_OF_CREATION
     *
     * @param SR_DATE_OF_CREATION the value for TDED_SUSPECT_REPORTS.SR_DATE_OF_CREATION
     *
     * @mbg.generated Tue Dec 15 16:02:14 GMT 2020
     */
    public void setSR_DATE_OF_CREATION(Date SR_DATE_OF_CREATION) {
        this.SR_DATE_OF_CREATION = SR_DATE_OF_CREATION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TDED_SUSPECT_REPORTS.SR_DATE_OF_COMPLETION
     *
     * @return the value of TDED_SUSPECT_REPORTS.SR_DATE_OF_COMPLETION
     *
     * @mbg.generated Tue Dec 15 16:02:14 GMT 2020
     */
    public Date getSR_DATE_OF_COMPLETION() {
        return SR_DATE_OF_COMPLETION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TDED_SUSPECT_REPORTS.SR_DATE_OF_COMPLETION
     *
     * @param SR_DATE_OF_COMPLETION the value for TDED_SUSPECT_REPORTS.SR_DATE_OF_COMPLETION
     *
     * @mbg.generated Tue Dec 15 16:02:14 GMT 2020
     */
    public void setSR_DATE_OF_COMPLETION(Date SR_DATE_OF_COMPLETION) {
        this.SR_DATE_OF_COMPLETION = SR_DATE_OF_COMPLETION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TDED_SUSPECT_REPORTS.SR_OUT_OF_HOURS_FLAG
     *
     * @return the value of TDED_SUSPECT_REPORTS.SR_OUT_OF_HOURS_FLAG
     *
     * @mbg.generated Tue Dec 15 16:02:14 GMT 2020
     */
    public String getSR_OUT_OF_HOURS_FLAG() {
        return SR_OUT_OF_HOURS_FLAG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TDED_SUSPECT_REPORTS.SR_OUT_OF_HOURS_FLAG
     *
     * @param SR_OUT_OF_HOURS_FLAG the value for TDED_SUSPECT_REPORTS.SR_OUT_OF_HOURS_FLAG
     *
     * @mbg.generated Tue Dec 15 16:02:14 GMT 2020
     */
    public void setSR_OUT_OF_HOURS_FLAG(String SR_OUT_OF_HOURS_FLAG) {
        this.SR_OUT_OF_HOURS_FLAG = SR_OUT_OF_HOURS_FLAG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TDED_SUSPECT_REPORTS.SR_NDCC_LDCC_NOTIFIED_NAME
     *
     * @return the value of TDED_SUSPECT_REPORTS.SR_NDCC_LDCC_NOTIFIED_NAME
     *
     * @mbg.generated Tue Dec 15 16:02:14 GMT 2020
     */
    public String getSR_NDCC_LDCC_NOTIFIED_NAME() {
        return SR_NDCC_LDCC_NOTIFIED_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TDED_SUSPECT_REPORTS.SR_NDCC_LDCC_NOTIFIED_NAME
     *
     * @param SR_NDCC_LDCC_NOTIFIED_NAME the value for TDED_SUSPECT_REPORTS.SR_NDCC_LDCC_NOTIFIED_NAME
     *
     * @mbg.generated Tue Dec 15 16:02:14 GMT 2020
     */
    public void setSR_NDCC_LDCC_NOTIFIED_NAME(String SR_NDCC_LDCC_NOTIFIED_NAME) {
        this.SR_NDCC_LDCC_NOTIFIED_NAME = SR_NDCC_LDCC_NOTIFIED_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TDED_SUSPECT_REPORTS.SR_CVRL_RVL_NOTIFIED_NAME
     *
     * @return the value of TDED_SUSPECT_REPORTS.SR_CVRL_RVL_NOTIFIED_NAME
     *
     * @mbg.generated Tue Dec 15 16:02:14 GMT 2020
     */
    public String getSR_CVRL_RVL_NOTIFIED_NAME() {
        return SR_CVRL_RVL_NOTIFIED_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TDED_SUSPECT_REPORTS.SR_CVRL_RVL_NOTIFIED_NAME
     *
     * @param SR_CVRL_RVL_NOTIFIED_NAME the value for TDED_SUSPECT_REPORTS.SR_CVRL_RVL_NOTIFIED_NAME
     *
     * @mbg.generated Tue Dec 15 16:02:14 GMT 2020
     */
    public void setSR_CVRL_RVL_NOTIFIED_NAME(String SR_CVRL_RVL_NOTIFIED_NAME) {
        this.SR_CVRL_RVL_NOTIFIED_NAME = SR_CVRL_RVL_NOTIFIED_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TDED_SUSPECT_REPORTS.SR_REGIONAL_SSVI_NOTIFIED_NAME
     *
     * @return the value of TDED_SUSPECT_REPORTS.SR_REGIONAL_SSVI_NOTIFIED_NAME
     *
     * @mbg.generated Tue Dec 15 16:02:14 GMT 2020
     */
    public String getSR_REGIONAL_SSVI_NOTIFIED_NAME() {
        return SR_REGIONAL_SSVI_NOTIFIED_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TDED_SUSPECT_REPORTS.SR_REGIONAL_SSVI_NOTIFIED_NAME
     *
     * @param SR_REGIONAL_SSVI_NOTIFIED_NAME the value for TDED_SUSPECT_REPORTS.SR_REGIONAL_SSVI_NOTIFIED_NAME
     *
     * @mbg.generated Tue Dec 15 16:02:14 GMT 2020
     */
    public void setSR_REGIONAL_SSVI_NOTIFIED_NAME(String SR_REGIONAL_SSVI_NOTIFIED_NAME) {
        this.SR_REGIONAL_SSVI_NOTIFIED_NAME = SR_REGIONAL_SSVI_NOTIFIED_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TDED_SUSPECT_REPORTS.SR_REGIONAL_SVI_NOTIFIED_NAME
     *
     * @return the value of TDED_SUSPECT_REPORTS.SR_REGIONAL_SVI_NOTIFIED_NAME
     *
     * @mbg.generated Tue Dec 15 16:02:14 GMT 2020
     */
    public String getSR_REGIONAL_SVI_NOTIFIED_NAME() {
        return SR_REGIONAL_SVI_NOTIFIED_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TDED_SUSPECT_REPORTS.SR_REGIONAL_SVI_NOTIFIED_NAME
     *
     * @param SR_REGIONAL_SVI_NOTIFIED_NAME the value for TDED_SUSPECT_REPORTS.SR_REGIONAL_SVI_NOTIFIED_NAME
     *
     * @mbg.generated Tue Dec 15 16:02:14 GMT 2020
     */
    public void setSR_REGIONAL_SVI_NOTIFIED_NAME(String SR_REGIONAL_SVI_NOTIFIED_NAME) {
        this.SR_REGIONAL_SVI_NOTIFIED_NAME = SR_REGIONAL_SVI_NOTIFIED_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TDED_SUSPECT_REPORTS.SR_VPHIS_SVI_NOTIFIED_NAME
     *
     * @return the value of TDED_SUSPECT_REPORTS.SR_VPHIS_SVI_NOTIFIED_NAME
     *
     * @mbg.generated Tue Dec 15 16:02:14 GMT 2020
     */
    public String getSR_VPHIS_SVI_NOTIFIED_NAME() {
        return SR_VPHIS_SVI_NOTIFIED_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TDED_SUSPECT_REPORTS.SR_VPHIS_SVI_NOTIFIED_NAME
     *
     * @param SR_VPHIS_SVI_NOTIFIED_NAME the value for TDED_SUSPECT_REPORTS.SR_VPHIS_SVI_NOTIFIED_NAME
     *
     * @mbg.generated Tue Dec 15 16:02:14 GMT 2020
     */
    public void setSR_VPHIS_SVI_NOTIFIED_NAME(String SR_VPHIS_SVI_NOTIFIED_NAME) {
        this.SR_VPHIS_SVI_NOTIFIED_NAME = SR_VPHIS_SVI_NOTIFIED_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TDED_SUSPECT_REPORTS.SR_AUDIT_USER
     *
     * @return the value of TDED_SUSPECT_REPORTS.SR_AUDIT_USER
     *
     * @mbg.generated Tue Dec 15 16:02:14 GMT 2020
     */
    public String getSR_AUDIT_USER() {
        return SR_AUDIT_USER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TDED_SUSPECT_REPORTS.SR_AUDIT_USER
     *
     * @param SR_AUDIT_USER the value for TDED_SUSPECT_REPORTS.SR_AUDIT_USER
     *
     * @mbg.generated Tue Dec 15 16:02:14 GMT 2020
     */
    public void setSR_AUDIT_USER(String SR_AUDIT_USER) {
        this.SR_AUDIT_USER = SR_AUDIT_USER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TDED_SUSPECT_REPORTS.SR_AUDIT_DATE
     *
     * @return the value of TDED_SUSPECT_REPORTS.SR_AUDIT_DATE
     *
     * @mbg.generated Tue Dec 15 16:02:14 GMT 2020
     */
    public Date getSR_AUDIT_DATE() {
        return SR_AUDIT_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TDED_SUSPECT_REPORTS.SR_AUDIT_DATE
     *
     * @param SR_AUDIT_DATE the value for TDED_SUSPECT_REPORTS.SR_AUDIT_DATE
     *
     * @mbg.generated Tue Dec 15 16:02:14 GMT 2020
     */
    public void setSR_AUDIT_DATE(Date SR_AUDIT_DATE) {
        this.SR_AUDIT_DATE = SR_AUDIT_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TDED_SUSPECT_REPORTS.SR_AUDIT_ACTION
     *
     * @return the value of TDED_SUSPECT_REPORTS.SR_AUDIT_ACTION
     *
     * @mbg.generated Tue Dec 15 16:02:14 GMT 2020
     */
    public String getSR_AUDIT_ACTION() {
        return SR_AUDIT_ACTION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TDED_SUSPECT_REPORTS.SR_AUDIT_ACTION
     *
     * @param SR_AUDIT_ACTION the value for TDED_SUSPECT_REPORTS.SR_AUDIT_ACTION
     *
     * @mbg.generated Tue Dec 15 16:02:14 GMT 2020
     */
    public void setSR_AUDIT_ACTION(String SR_AUDIT_ACTION) {
        this.SR_AUDIT_ACTION = SR_AUDIT_ACTION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TDED_SUSPECT_REPORTS.SR_VER_NUM
     *
     * @return the value of TDED_SUSPECT_REPORTS.SR_VER_NUM
     *
     * @mbg.generated Tue Dec 15 16:02:14 GMT 2020
     */
    public Short getSR_VER_NUM() {
        return SR_VER_NUM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TDED_SUSPECT_REPORTS.SR_VER_NUM
     *
     * @param SR_VER_NUM the value for TDED_SUSPECT_REPORTS.SR_VER_NUM
     *
     * @mbg.generated Tue Dec 15 16:02:14 GMT 2020
     */
    public void setSR_VER_NUM(Short SR_VER_NUM) {
        this.SR_VER_NUM = SR_VER_NUM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TDED_SUSPECT_REPORTS.SR_AUDIT_CREATE_USER
     *
     * @return the value of TDED_SUSPECT_REPORTS.SR_AUDIT_CREATE_USER
     *
     * @mbg.generated Tue Dec 15 16:02:14 GMT 2020
     */
    public String getSR_AUDIT_CREATE_USER() {
        return SR_AUDIT_CREATE_USER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TDED_SUSPECT_REPORTS.SR_AUDIT_CREATE_USER
     *
     * @param SR_AUDIT_CREATE_USER the value for TDED_SUSPECT_REPORTS.SR_AUDIT_CREATE_USER
     *
     * @mbg.generated Tue Dec 15 16:02:14 GMT 2020
     */
    public void setSR_AUDIT_CREATE_USER(String SR_AUDIT_CREATE_USER) {
        this.SR_AUDIT_CREATE_USER = SR_AUDIT_CREATE_USER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TDED_SUSPECT_REPORTS.SR_AUDIT_CREATE_DATE
     *
     * @return the value of TDED_SUSPECT_REPORTS.SR_AUDIT_CREATE_DATE
     *
     * @mbg.generated Tue Dec 15 16:02:14 GMT 2020
     */
    public Date getSR_AUDIT_CREATE_DATE() {
        return SR_AUDIT_CREATE_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TDED_SUSPECT_REPORTS.SR_AUDIT_CREATE_DATE
     *
     * @param SR_AUDIT_CREATE_DATE the value for TDED_SUSPECT_REPORTS.SR_AUDIT_CREATE_DATE
     *
     * @mbg.generated Tue Dec 15 16:02:14 GMT 2020
     */
    public void setSR_AUDIT_CREATE_DATE(Date SR_AUDIT_CREATE_DATE) {
        this.SR_AUDIT_CREATE_DATE = SR_AUDIT_CREATE_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TDED_SUSPECT_REPORTS.SR_AUDIT_LOCATION
     *
     * @return the value of TDED_SUSPECT_REPORTS.SR_AUDIT_LOCATION
     *
     * @mbg.generated Tue Dec 15 16:02:14 GMT 2020
     */
    public String getSR_AUDIT_LOCATION() {
        return SR_AUDIT_LOCATION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TDED_SUSPECT_REPORTS.SR_AUDIT_LOCATION
     *
     * @param SR_AUDIT_LOCATION the value for TDED_SUSPECT_REPORTS.SR_AUDIT_LOCATION
     *
     * @mbg.generated Tue Dec 15 16:02:14 GMT 2020
     */
    public void setSR_AUDIT_LOCATION(String SR_AUDIT_LOCATION) {
        this.SR_AUDIT_LOCATION = SR_AUDIT_LOCATION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TDED_SUSPECT_REPORTS.SR_PREM_ID
     *
     * @return the value of TDED_SUSPECT_REPORTS.SR_PREM_ID
     *
     * @mbg.generated Tue Dec 15 16:02:14 GMT 2020
     */
    public Short getSR_PREM_ID() {
        return SR_PREM_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TDED_SUSPECT_REPORTS.SR_PREM_ID
     *
     * @param SR_PREM_ID the value for TDED_SUSPECT_REPORTS.SR_PREM_ID
     *
     * @mbg.generated Tue Dec 15 16:02:14 GMT 2020
     */
    public void setSR_PREM_ID(Short SR_PREM_ID) {
        this.SR_PREM_ID = SR_PREM_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TDED_SUSPECT_REPORTS.SR_JPA_UPDATED_BY
     *
     * @return the value of TDED_SUSPECT_REPORTS.SR_JPA_UPDATED_BY
     *
     * @mbg.generated Tue Dec 15 16:02:14 GMT 2020
     */
    public String getSR_JPA_UPDATED_BY() {
        return SR_JPA_UPDATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TDED_SUSPECT_REPORTS.SR_JPA_UPDATED_BY
     *
     * @param SR_JPA_UPDATED_BY the value for TDED_SUSPECT_REPORTS.SR_JPA_UPDATED_BY
     *
     * @mbg.generated Tue Dec 15 16:02:14 GMT 2020
     */
    public void setSR_JPA_UPDATED_BY(String SR_JPA_UPDATED_BY) {
        this.SR_JPA_UPDATED_BY = SR_JPA_UPDATED_BY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TDED_SUSPECT_REPORTS.SR_JPA_UPDATED_DATE
     *
     * @return the value of TDED_SUSPECT_REPORTS.SR_JPA_UPDATED_DATE
     *
     * @mbg.generated Tue Dec 15 16:02:14 GMT 2020
     */
    public Date getSR_JPA_UPDATED_DATE() {
        return SR_JPA_UPDATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TDED_SUSPECT_REPORTS.SR_JPA_UPDATED_DATE
     *
     * @param SR_JPA_UPDATED_DATE the value for TDED_SUSPECT_REPORTS.SR_JPA_UPDATED_DATE
     *
     * @mbg.generated Tue Dec 15 16:02:14 GMT 2020
     */
    public void setSR_JPA_UPDATED_DATE(Date SR_JPA_UPDATED_DATE) {
        this.SR_JPA_UPDATED_DATE = SR_JPA_UPDATED_DATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TDED_SUSPECT_REPORTS.SR_JPA_VERSION
     *
     * @return the value of TDED_SUSPECT_REPORTS.SR_JPA_VERSION
     *
     * @mbg.generated Tue Dec 15 16:02:14 GMT 2020
     */
    public Short getSR_JPA_VERSION() {
        return SR_JPA_VERSION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TDED_SUSPECT_REPORTS.SR_JPA_VERSION
     *
     * @param SR_JPA_VERSION the value for TDED_SUSPECT_REPORTS.SR_JPA_VERSION
     *
     * @mbg.generated Tue Dec 15 16:02:14 GMT 2020
     */
    public void setSR_JPA_VERSION(Short SR_JPA_VERSION) {
        this.SR_JPA_VERSION = SR_JPA_VERSION;
    }
}