package com.expleoautomation.dao;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TDED_SUSPECT_REPORTSExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TDED_SUSPECT_REPORTS
     *
     * @mbg.generated Tue Dec 15 16:02:14 GMT 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TDED_SUSPECT_REPORTS
     *
     * @mbg.generated Tue Dec 15 16:02:14 GMT 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TDED_SUSPECT_REPORTS
     *
     * @mbg.generated Tue Dec 15 16:02:14 GMT 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TDED_SUSPECT_REPORTS
     *
     * @mbg.generated Tue Dec 15 16:02:14 GMT 2020
     */
    public TDED_SUSPECT_REPORTSExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TDED_SUSPECT_REPORTS
     *
     * @mbg.generated Tue Dec 15 16:02:14 GMT 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TDED_SUSPECT_REPORTS
     *
     * @mbg.generated Tue Dec 15 16:02:14 GMT 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TDED_SUSPECT_REPORTS
     *
     * @mbg.generated Tue Dec 15 16:02:14 GMT 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TDED_SUSPECT_REPORTS
     *
     * @mbg.generated Tue Dec 15 16:02:14 GMT 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TDED_SUSPECT_REPORTS
     *
     * @mbg.generated Tue Dec 15 16:02:14 GMT 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TDED_SUSPECT_REPORTS
     *
     * @mbg.generated Tue Dec 15 16:02:14 GMT 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TDED_SUSPECT_REPORTS
     *
     * @mbg.generated Tue Dec 15 16:02:14 GMT 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TDED_SUSPECT_REPORTS
     *
     * @mbg.generated Tue Dec 15 16:02:14 GMT 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TDED_SUSPECT_REPORTS
     *
     * @mbg.generated Tue Dec 15 16:02:14 GMT 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TDED_SUSPECT_REPORTS
     *
     * @mbg.generated Tue Dec 15 16:02:14 GMT 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TDED_SUSPECT_REPORTS
     *
     * @mbg.generated Tue Dec 15 16:02:14 GMT 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSR_IDIsNull() {
            addCriterion("SR_ID is null");
            return (Criteria) this;
        }

        public Criteria andSR_IDIsNotNull() {
            addCriterion("SR_ID is not null");
            return (Criteria) this;
        }

        public Criteria andSR_IDEqualTo(Short value) {
            addCriterion("SR_ID =", value, "SR_ID");
            return (Criteria) this;
        }

        public Criteria andSR_IDNotEqualTo(Short value) {
            addCriterion("SR_ID <>", value, "SR_ID");
            return (Criteria) this;
        }

        public Criteria andSR_IDGreaterThan(Short value) {
            addCriterion("SR_ID >", value, "SR_ID");
            return (Criteria) this;
        }

        public Criteria andSR_IDGreaterThanOrEqualTo(Short value) {
            addCriterion("SR_ID >=", value, "SR_ID");
            return (Criteria) this;
        }

        public Criteria andSR_IDLessThan(Short value) {
            addCriterion("SR_ID <", value, "SR_ID");
            return (Criteria) this;
        }

        public Criteria andSR_IDLessThanOrEqualTo(Short value) {
            addCriterion("SR_ID <=", value, "SR_ID");
            return (Criteria) this;
        }

        public Criteria andSR_IDIn(List<Short> values) {
            addCriterion("SR_ID in", values, "SR_ID");
            return (Criteria) this;
        }

        public Criteria andSR_IDNotIn(List<Short> values) {
            addCriterion("SR_ID not in", values, "SR_ID");
            return (Criteria) this;
        }

        public Criteria andSR_IDBetween(Short value1, Short value2) {
            addCriterion("SR_ID between", value1, value2, "SR_ID");
            return (Criteria) this;
        }

        public Criteria andSR_IDNotBetween(Short value1, Short value2) {
            addCriterion("SR_ID not between", value1, value2, "SR_ID");
            return (Criteria) this;
        }

        public Criteria andSR_CASE_IDIsNull() {
            addCriterion("SR_CASE_ID is null");
            return (Criteria) this;
        }

        public Criteria andSR_CASE_IDIsNotNull() {
            addCriterion("SR_CASE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andSR_CASE_IDEqualTo(Short value) {
            addCriterion("SR_CASE_ID =", value, "SR_CASE_ID");
            return (Criteria) this;
        }

        public Criteria andSR_CASE_IDNotEqualTo(Short value) {
            addCriterion("SR_CASE_ID <>", value, "SR_CASE_ID");
            return (Criteria) this;
        }

        public Criteria andSR_CASE_IDGreaterThan(Short value) {
            addCriterion("SR_CASE_ID >", value, "SR_CASE_ID");
            return (Criteria) this;
        }

        public Criteria andSR_CASE_IDGreaterThanOrEqualTo(Short value) {
            addCriterion("SR_CASE_ID >=", value, "SR_CASE_ID");
            return (Criteria) this;
        }

        public Criteria andSR_CASE_IDLessThan(Short value) {
            addCriterion("SR_CASE_ID <", value, "SR_CASE_ID");
            return (Criteria) this;
        }

        public Criteria andSR_CASE_IDLessThanOrEqualTo(Short value) {
            addCriterion("SR_CASE_ID <=", value, "SR_CASE_ID");
            return (Criteria) this;
        }

        public Criteria andSR_CASE_IDIn(List<Short> values) {
            addCriterion("SR_CASE_ID in", values, "SR_CASE_ID");
            return (Criteria) this;
        }

        public Criteria andSR_CASE_IDNotIn(List<Short> values) {
            addCriterion("SR_CASE_ID not in", values, "SR_CASE_ID");
            return (Criteria) this;
        }

        public Criteria andSR_CASE_IDBetween(Short value1, Short value2) {
            addCriterion("SR_CASE_ID between", value1, value2, "SR_CASE_ID");
            return (Criteria) this;
        }

        public Criteria andSR_CASE_IDNotBetween(Short value1, Short value2) {
            addCriterion("SR_CASE_ID not between", value1, value2, "SR_CASE_ID");
            return (Criteria) this;
        }

        public Criteria andSR_STATUSIsNull() {
            addCriterion("SR_STATUS is null");
            return (Criteria) this;
        }

        public Criteria andSR_STATUSIsNotNull() {
            addCriterion("SR_STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andSR_STATUSEqualTo(Short value) {
            addCriterion("SR_STATUS =", value, "SR_STATUS");
            return (Criteria) this;
        }

        public Criteria andSR_STATUSNotEqualTo(Short value) {
            addCriterion("SR_STATUS <>", value, "SR_STATUS");
            return (Criteria) this;
        }

        public Criteria andSR_STATUSGreaterThan(Short value) {
            addCriterion("SR_STATUS >", value, "SR_STATUS");
            return (Criteria) this;
        }

        public Criteria andSR_STATUSGreaterThanOrEqualTo(Short value) {
            addCriterion("SR_STATUS >=", value, "SR_STATUS");
            return (Criteria) this;
        }

        public Criteria andSR_STATUSLessThan(Short value) {
            addCriterion("SR_STATUS <", value, "SR_STATUS");
            return (Criteria) this;
        }

        public Criteria andSR_STATUSLessThanOrEqualTo(Short value) {
            addCriterion("SR_STATUS <=", value, "SR_STATUS");
            return (Criteria) this;
        }

        public Criteria andSR_STATUSIn(List<Short> values) {
            addCriterion("SR_STATUS in", values, "SR_STATUS");
            return (Criteria) this;
        }

        public Criteria andSR_STATUSNotIn(List<Short> values) {
            addCriterion("SR_STATUS not in", values, "SR_STATUS");
            return (Criteria) this;
        }

        public Criteria andSR_STATUSBetween(Short value1, Short value2) {
            addCriterion("SR_STATUS between", value1, value2, "SR_STATUS");
            return (Criteria) this;
        }

        public Criteria andSR_STATUSNotBetween(Short value1, Short value2) {
            addCriterion("SR_STATUS not between", value1, value2, "SR_STATUS");
            return (Criteria) this;
        }

        public Criteria andSR_DATE_OF_CREATIONIsNull() {
            addCriterion("SR_DATE_OF_CREATION is null");
            return (Criteria) this;
        }

        public Criteria andSR_DATE_OF_CREATIONIsNotNull() {
            addCriterion("SR_DATE_OF_CREATION is not null");
            return (Criteria) this;
        }

        public Criteria andSR_DATE_OF_CREATIONEqualTo(Date value) {
            addCriterion("SR_DATE_OF_CREATION =", value, "SR_DATE_OF_CREATION");
            return (Criteria) this;
        }

        public Criteria andSR_DATE_OF_CREATIONNotEqualTo(Date value) {
            addCriterion("SR_DATE_OF_CREATION <>", value, "SR_DATE_OF_CREATION");
            return (Criteria) this;
        }

        public Criteria andSR_DATE_OF_CREATIONGreaterThan(Date value) {
            addCriterion("SR_DATE_OF_CREATION >", value, "SR_DATE_OF_CREATION");
            return (Criteria) this;
        }

        public Criteria andSR_DATE_OF_CREATIONGreaterThanOrEqualTo(Date value) {
            addCriterion("SR_DATE_OF_CREATION >=", value, "SR_DATE_OF_CREATION");
            return (Criteria) this;
        }

        public Criteria andSR_DATE_OF_CREATIONLessThan(Date value) {
            addCriterion("SR_DATE_OF_CREATION <", value, "SR_DATE_OF_CREATION");
            return (Criteria) this;
        }

        public Criteria andSR_DATE_OF_CREATIONLessThanOrEqualTo(Date value) {
            addCriterion("SR_DATE_OF_CREATION <=", value, "SR_DATE_OF_CREATION");
            return (Criteria) this;
        }

        public Criteria andSR_DATE_OF_CREATIONIn(List<Date> values) {
            addCriterion("SR_DATE_OF_CREATION in", values, "SR_DATE_OF_CREATION");
            return (Criteria) this;
        }

        public Criteria andSR_DATE_OF_CREATIONNotIn(List<Date> values) {
            addCriterion("SR_DATE_OF_CREATION not in", values, "SR_DATE_OF_CREATION");
            return (Criteria) this;
        }

        public Criteria andSR_DATE_OF_CREATIONBetween(Date value1, Date value2) {
            addCriterion("SR_DATE_OF_CREATION between", value1, value2, "SR_DATE_OF_CREATION");
            return (Criteria) this;
        }

        public Criteria andSR_DATE_OF_CREATIONNotBetween(Date value1, Date value2) {
            addCriterion("SR_DATE_OF_CREATION not between", value1, value2, "SR_DATE_OF_CREATION");
            return (Criteria) this;
        }

        public Criteria andSR_DATE_OF_COMPLETIONIsNull() {
            addCriterion("SR_DATE_OF_COMPLETION is null");
            return (Criteria) this;
        }

        public Criteria andSR_DATE_OF_COMPLETIONIsNotNull() {
            addCriterion("SR_DATE_OF_COMPLETION is not null");
            return (Criteria) this;
        }

        public Criteria andSR_DATE_OF_COMPLETIONEqualTo(Date value) {
            addCriterion("SR_DATE_OF_COMPLETION =", value, "SR_DATE_OF_COMPLETION");
            return (Criteria) this;
        }

        public Criteria andSR_DATE_OF_COMPLETIONNotEqualTo(Date value) {
            addCriterion("SR_DATE_OF_COMPLETION <>", value, "SR_DATE_OF_COMPLETION");
            return (Criteria) this;
        }

        public Criteria andSR_DATE_OF_COMPLETIONGreaterThan(Date value) {
            addCriterion("SR_DATE_OF_COMPLETION >", value, "SR_DATE_OF_COMPLETION");
            return (Criteria) this;
        }

        public Criteria andSR_DATE_OF_COMPLETIONGreaterThanOrEqualTo(Date value) {
            addCriterion("SR_DATE_OF_COMPLETION >=", value, "SR_DATE_OF_COMPLETION");
            return (Criteria) this;
        }

        public Criteria andSR_DATE_OF_COMPLETIONLessThan(Date value) {
            addCriterion("SR_DATE_OF_COMPLETION <", value, "SR_DATE_OF_COMPLETION");
            return (Criteria) this;
        }

        public Criteria andSR_DATE_OF_COMPLETIONLessThanOrEqualTo(Date value) {
            addCriterion("SR_DATE_OF_COMPLETION <=", value, "SR_DATE_OF_COMPLETION");
            return (Criteria) this;
        }

        public Criteria andSR_DATE_OF_COMPLETIONIn(List<Date> values) {
            addCriterion("SR_DATE_OF_COMPLETION in", values, "SR_DATE_OF_COMPLETION");
            return (Criteria) this;
        }

        public Criteria andSR_DATE_OF_COMPLETIONNotIn(List<Date> values) {
            addCriterion("SR_DATE_OF_COMPLETION not in", values, "SR_DATE_OF_COMPLETION");
            return (Criteria) this;
        }

        public Criteria andSR_DATE_OF_COMPLETIONBetween(Date value1, Date value2) {
            addCriterion("SR_DATE_OF_COMPLETION between", value1, value2, "SR_DATE_OF_COMPLETION");
            return (Criteria) this;
        }

        public Criteria andSR_DATE_OF_COMPLETIONNotBetween(Date value1, Date value2) {
            addCriterion("SR_DATE_OF_COMPLETION not between", value1, value2, "SR_DATE_OF_COMPLETION");
            return (Criteria) this;
        }

        public Criteria andSR_OUT_OF_HOURS_FLAGIsNull() {
            addCriterion("SR_OUT_OF_HOURS_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andSR_OUT_OF_HOURS_FLAGIsNotNull() {
            addCriterion("SR_OUT_OF_HOURS_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andSR_OUT_OF_HOURS_FLAGEqualTo(String value) {
            addCriterion("SR_OUT_OF_HOURS_FLAG =", value, "SR_OUT_OF_HOURS_FLAG");
            return (Criteria) this;
        }

        public Criteria andSR_OUT_OF_HOURS_FLAGNotEqualTo(String value) {
            addCriterion("SR_OUT_OF_HOURS_FLAG <>", value, "SR_OUT_OF_HOURS_FLAG");
            return (Criteria) this;
        }

        public Criteria andSR_OUT_OF_HOURS_FLAGGreaterThan(String value) {
            addCriterion("SR_OUT_OF_HOURS_FLAG >", value, "SR_OUT_OF_HOURS_FLAG");
            return (Criteria) this;
        }

        public Criteria andSR_OUT_OF_HOURS_FLAGGreaterThanOrEqualTo(String value) {
            addCriterion("SR_OUT_OF_HOURS_FLAG >=", value, "SR_OUT_OF_HOURS_FLAG");
            return (Criteria) this;
        }

        public Criteria andSR_OUT_OF_HOURS_FLAGLessThan(String value) {
            addCriterion("SR_OUT_OF_HOURS_FLAG <", value, "SR_OUT_OF_HOURS_FLAG");
            return (Criteria) this;
        }

        public Criteria andSR_OUT_OF_HOURS_FLAGLessThanOrEqualTo(String value) {
            addCriterion("SR_OUT_OF_HOURS_FLAG <=", value, "SR_OUT_OF_HOURS_FLAG");
            return (Criteria) this;
        }

        public Criteria andSR_OUT_OF_HOURS_FLAGLike(String value) {
            addCriterion("SR_OUT_OF_HOURS_FLAG like", value, "SR_OUT_OF_HOURS_FLAG");
            return (Criteria) this;
        }

        public Criteria andSR_OUT_OF_HOURS_FLAGNotLike(String value) {
            addCriterion("SR_OUT_OF_HOURS_FLAG not like", value, "SR_OUT_OF_HOURS_FLAG");
            return (Criteria) this;
        }

        public Criteria andSR_OUT_OF_HOURS_FLAGIn(List<String> values) {
            addCriterion("SR_OUT_OF_HOURS_FLAG in", values, "SR_OUT_OF_HOURS_FLAG");
            return (Criteria) this;
        }

        public Criteria andSR_OUT_OF_HOURS_FLAGNotIn(List<String> values) {
            addCriterion("SR_OUT_OF_HOURS_FLAG not in", values, "SR_OUT_OF_HOURS_FLAG");
            return (Criteria) this;
        }

        public Criteria andSR_OUT_OF_HOURS_FLAGBetween(String value1, String value2) {
            addCriterion("SR_OUT_OF_HOURS_FLAG between", value1, value2, "SR_OUT_OF_HOURS_FLAG");
            return (Criteria) this;
        }

        public Criteria andSR_OUT_OF_HOURS_FLAGNotBetween(String value1, String value2) {
            addCriterion("SR_OUT_OF_HOURS_FLAG not between", value1, value2, "SR_OUT_OF_HOURS_FLAG");
            return (Criteria) this;
        }

        public Criteria andSR_NDCC_LDCC_NOTIFIED_NAMEIsNull() {
            addCriterion("SR_NDCC_LDCC_NOTIFIED_NAME is null");
            return (Criteria) this;
        }

        public Criteria andSR_NDCC_LDCC_NOTIFIED_NAMEIsNotNull() {
            addCriterion("SR_NDCC_LDCC_NOTIFIED_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andSR_NDCC_LDCC_NOTIFIED_NAMEEqualTo(String value) {
            addCriterion("SR_NDCC_LDCC_NOTIFIED_NAME =", value, "SR_NDCC_LDCC_NOTIFIED_NAME");
            return (Criteria) this;
        }

        public Criteria andSR_NDCC_LDCC_NOTIFIED_NAMENotEqualTo(String value) {
            addCriterion("SR_NDCC_LDCC_NOTIFIED_NAME <>", value, "SR_NDCC_LDCC_NOTIFIED_NAME");
            return (Criteria) this;
        }

        public Criteria andSR_NDCC_LDCC_NOTIFIED_NAMEGreaterThan(String value) {
            addCriterion("SR_NDCC_LDCC_NOTIFIED_NAME >", value, "SR_NDCC_LDCC_NOTIFIED_NAME");
            return (Criteria) this;
        }

        public Criteria andSR_NDCC_LDCC_NOTIFIED_NAMEGreaterThanOrEqualTo(String value) {
            addCriterion("SR_NDCC_LDCC_NOTIFIED_NAME >=", value, "SR_NDCC_LDCC_NOTIFIED_NAME");
            return (Criteria) this;
        }

        public Criteria andSR_NDCC_LDCC_NOTIFIED_NAMELessThan(String value) {
            addCriterion("SR_NDCC_LDCC_NOTIFIED_NAME <", value, "SR_NDCC_LDCC_NOTIFIED_NAME");
            return (Criteria) this;
        }

        public Criteria andSR_NDCC_LDCC_NOTIFIED_NAMELessThanOrEqualTo(String value) {
            addCriterion("SR_NDCC_LDCC_NOTIFIED_NAME <=", value, "SR_NDCC_LDCC_NOTIFIED_NAME");
            return (Criteria) this;
        }

        public Criteria andSR_NDCC_LDCC_NOTIFIED_NAMELike(String value) {
            addCriterion("SR_NDCC_LDCC_NOTIFIED_NAME like", value, "SR_NDCC_LDCC_NOTIFIED_NAME");
            return (Criteria) this;
        }

        public Criteria andSR_NDCC_LDCC_NOTIFIED_NAMENotLike(String value) {
            addCriterion("SR_NDCC_LDCC_NOTIFIED_NAME not like", value, "SR_NDCC_LDCC_NOTIFIED_NAME");
            return (Criteria) this;
        }

        public Criteria andSR_NDCC_LDCC_NOTIFIED_NAMEIn(List<String> values) {
            addCriterion("SR_NDCC_LDCC_NOTIFIED_NAME in", values, "SR_NDCC_LDCC_NOTIFIED_NAME");
            return (Criteria) this;
        }

        public Criteria andSR_NDCC_LDCC_NOTIFIED_NAMENotIn(List<String> values) {
            addCriterion("SR_NDCC_LDCC_NOTIFIED_NAME not in", values, "SR_NDCC_LDCC_NOTIFIED_NAME");
            return (Criteria) this;
        }

        public Criteria andSR_NDCC_LDCC_NOTIFIED_NAMEBetween(String value1, String value2) {
            addCriterion("SR_NDCC_LDCC_NOTIFIED_NAME between", value1, value2, "SR_NDCC_LDCC_NOTIFIED_NAME");
            return (Criteria) this;
        }

        public Criteria andSR_NDCC_LDCC_NOTIFIED_NAMENotBetween(String value1, String value2) {
            addCriterion("SR_NDCC_LDCC_NOTIFIED_NAME not between", value1, value2, "SR_NDCC_LDCC_NOTIFIED_NAME");
            return (Criteria) this;
        }

        public Criteria andSR_CVRL_RVL_NOTIFIED_NAMEIsNull() {
            addCriterion("SR_CVRL_RVL_NOTIFIED_NAME is null");
            return (Criteria) this;
        }

        public Criteria andSR_CVRL_RVL_NOTIFIED_NAMEIsNotNull() {
            addCriterion("SR_CVRL_RVL_NOTIFIED_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andSR_CVRL_RVL_NOTIFIED_NAMEEqualTo(String value) {
            addCriterion("SR_CVRL_RVL_NOTIFIED_NAME =", value, "SR_CVRL_RVL_NOTIFIED_NAME");
            return (Criteria) this;
        }

        public Criteria andSR_CVRL_RVL_NOTIFIED_NAMENotEqualTo(String value) {
            addCriterion("SR_CVRL_RVL_NOTIFIED_NAME <>", value, "SR_CVRL_RVL_NOTIFIED_NAME");
            return (Criteria) this;
        }

        public Criteria andSR_CVRL_RVL_NOTIFIED_NAMEGreaterThan(String value) {
            addCriterion("SR_CVRL_RVL_NOTIFIED_NAME >", value, "SR_CVRL_RVL_NOTIFIED_NAME");
            return (Criteria) this;
        }

        public Criteria andSR_CVRL_RVL_NOTIFIED_NAMEGreaterThanOrEqualTo(String value) {
            addCriterion("SR_CVRL_RVL_NOTIFIED_NAME >=", value, "SR_CVRL_RVL_NOTIFIED_NAME");
            return (Criteria) this;
        }

        public Criteria andSR_CVRL_RVL_NOTIFIED_NAMELessThan(String value) {
            addCriterion("SR_CVRL_RVL_NOTIFIED_NAME <", value, "SR_CVRL_RVL_NOTIFIED_NAME");
            return (Criteria) this;
        }

        public Criteria andSR_CVRL_RVL_NOTIFIED_NAMELessThanOrEqualTo(String value) {
            addCriterion("SR_CVRL_RVL_NOTIFIED_NAME <=", value, "SR_CVRL_RVL_NOTIFIED_NAME");
            return (Criteria) this;
        }

        public Criteria andSR_CVRL_RVL_NOTIFIED_NAMELike(String value) {
            addCriterion("SR_CVRL_RVL_NOTIFIED_NAME like", value, "SR_CVRL_RVL_NOTIFIED_NAME");
            return (Criteria) this;
        }

        public Criteria andSR_CVRL_RVL_NOTIFIED_NAMENotLike(String value) {
            addCriterion("SR_CVRL_RVL_NOTIFIED_NAME not like", value, "SR_CVRL_RVL_NOTIFIED_NAME");
            return (Criteria) this;
        }

        public Criteria andSR_CVRL_RVL_NOTIFIED_NAMEIn(List<String> values) {
            addCriterion("SR_CVRL_RVL_NOTIFIED_NAME in", values, "SR_CVRL_RVL_NOTIFIED_NAME");
            return (Criteria) this;
        }

        public Criteria andSR_CVRL_RVL_NOTIFIED_NAMENotIn(List<String> values) {
            addCriterion("SR_CVRL_RVL_NOTIFIED_NAME not in", values, "SR_CVRL_RVL_NOTIFIED_NAME");
            return (Criteria) this;
        }

        public Criteria andSR_CVRL_RVL_NOTIFIED_NAMEBetween(String value1, String value2) {
            addCriterion("SR_CVRL_RVL_NOTIFIED_NAME between", value1, value2, "SR_CVRL_RVL_NOTIFIED_NAME");
            return (Criteria) this;
        }

        public Criteria andSR_CVRL_RVL_NOTIFIED_NAMENotBetween(String value1, String value2) {
            addCriterion("SR_CVRL_RVL_NOTIFIED_NAME not between", value1, value2, "SR_CVRL_RVL_NOTIFIED_NAME");
            return (Criteria) this;
        }

        public Criteria andSR_REGIONAL_SSVI_NOTIFIED_NAMEIsNull() {
            addCriterion("SR_REGIONAL_SSVI_NOTIFIED_NAME is null");
            return (Criteria) this;
        }

        public Criteria andSR_REGIONAL_SSVI_NOTIFIED_NAMEIsNotNull() {
            addCriterion("SR_REGIONAL_SSVI_NOTIFIED_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andSR_REGIONAL_SSVI_NOTIFIED_NAMEEqualTo(String value) {
            addCriterion("SR_REGIONAL_SSVI_NOTIFIED_NAME =", value, "SR_REGIONAL_SSVI_NOTIFIED_NAME");
            return (Criteria) this;
        }

        public Criteria andSR_REGIONAL_SSVI_NOTIFIED_NAMENotEqualTo(String value) {
            addCriterion("SR_REGIONAL_SSVI_NOTIFIED_NAME <>", value, "SR_REGIONAL_SSVI_NOTIFIED_NAME");
            return (Criteria) this;
        }

        public Criteria andSR_REGIONAL_SSVI_NOTIFIED_NAMEGreaterThan(String value) {
            addCriterion("SR_REGIONAL_SSVI_NOTIFIED_NAME >", value, "SR_REGIONAL_SSVI_NOTIFIED_NAME");
            return (Criteria) this;
        }

        public Criteria andSR_REGIONAL_SSVI_NOTIFIED_NAMEGreaterThanOrEqualTo(String value) {
            addCriterion("SR_REGIONAL_SSVI_NOTIFIED_NAME >=", value, "SR_REGIONAL_SSVI_NOTIFIED_NAME");
            return (Criteria) this;
        }

        public Criteria andSR_REGIONAL_SSVI_NOTIFIED_NAMELessThan(String value) {
            addCriterion("SR_REGIONAL_SSVI_NOTIFIED_NAME <", value, "SR_REGIONAL_SSVI_NOTIFIED_NAME");
            return (Criteria) this;
        }

        public Criteria andSR_REGIONAL_SSVI_NOTIFIED_NAMELessThanOrEqualTo(String value) {
            addCriterion("SR_REGIONAL_SSVI_NOTIFIED_NAME <=", value, "SR_REGIONAL_SSVI_NOTIFIED_NAME");
            return (Criteria) this;
        }

        public Criteria andSR_REGIONAL_SSVI_NOTIFIED_NAMELike(String value) {
            addCriterion("SR_REGIONAL_SSVI_NOTIFIED_NAME like", value, "SR_REGIONAL_SSVI_NOTIFIED_NAME");
            return (Criteria) this;
        }

        public Criteria andSR_REGIONAL_SSVI_NOTIFIED_NAMENotLike(String value) {
            addCriterion("SR_REGIONAL_SSVI_NOTIFIED_NAME not like", value, "SR_REGIONAL_SSVI_NOTIFIED_NAME");
            return (Criteria) this;
        }

        public Criteria andSR_REGIONAL_SSVI_NOTIFIED_NAMEIn(List<String> values) {
            addCriterion("SR_REGIONAL_SSVI_NOTIFIED_NAME in", values, "SR_REGIONAL_SSVI_NOTIFIED_NAME");
            return (Criteria) this;
        }

        public Criteria andSR_REGIONAL_SSVI_NOTIFIED_NAMENotIn(List<String> values) {
            addCriterion("SR_REGIONAL_SSVI_NOTIFIED_NAME not in", values, "SR_REGIONAL_SSVI_NOTIFIED_NAME");
            return (Criteria) this;
        }

        public Criteria andSR_REGIONAL_SSVI_NOTIFIED_NAMEBetween(String value1, String value2) {
            addCriterion("SR_REGIONAL_SSVI_NOTIFIED_NAME between", value1, value2, "SR_REGIONAL_SSVI_NOTIFIED_NAME");
            return (Criteria) this;
        }

        public Criteria andSR_REGIONAL_SSVI_NOTIFIED_NAMENotBetween(String value1, String value2) {
            addCriterion("SR_REGIONAL_SSVI_NOTIFIED_NAME not between", value1, value2, "SR_REGIONAL_SSVI_NOTIFIED_NAME");
            return (Criteria) this;
        }

        public Criteria andSR_REGIONAL_SVI_NOTIFIED_NAMEIsNull() {
            addCriterion("SR_REGIONAL_SVI_NOTIFIED_NAME is null");
            return (Criteria) this;
        }

        public Criteria andSR_REGIONAL_SVI_NOTIFIED_NAMEIsNotNull() {
            addCriterion("SR_REGIONAL_SVI_NOTIFIED_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andSR_REGIONAL_SVI_NOTIFIED_NAMEEqualTo(String value) {
            addCriterion("SR_REGIONAL_SVI_NOTIFIED_NAME =", value, "SR_REGIONAL_SVI_NOTIFIED_NAME");
            return (Criteria) this;
        }

        public Criteria andSR_REGIONAL_SVI_NOTIFIED_NAMENotEqualTo(String value) {
            addCriterion("SR_REGIONAL_SVI_NOTIFIED_NAME <>", value, "SR_REGIONAL_SVI_NOTIFIED_NAME");
            return (Criteria) this;
        }

        public Criteria andSR_REGIONAL_SVI_NOTIFIED_NAMEGreaterThan(String value) {
            addCriterion("SR_REGIONAL_SVI_NOTIFIED_NAME >", value, "SR_REGIONAL_SVI_NOTIFIED_NAME");
            return (Criteria) this;
        }

        public Criteria andSR_REGIONAL_SVI_NOTIFIED_NAMEGreaterThanOrEqualTo(String value) {
            addCriterion("SR_REGIONAL_SVI_NOTIFIED_NAME >=", value, "SR_REGIONAL_SVI_NOTIFIED_NAME");
            return (Criteria) this;
        }

        public Criteria andSR_REGIONAL_SVI_NOTIFIED_NAMELessThan(String value) {
            addCriterion("SR_REGIONAL_SVI_NOTIFIED_NAME <", value, "SR_REGIONAL_SVI_NOTIFIED_NAME");
            return (Criteria) this;
        }

        public Criteria andSR_REGIONAL_SVI_NOTIFIED_NAMELessThanOrEqualTo(String value) {
            addCriterion("SR_REGIONAL_SVI_NOTIFIED_NAME <=", value, "SR_REGIONAL_SVI_NOTIFIED_NAME");
            return (Criteria) this;
        }

        public Criteria andSR_REGIONAL_SVI_NOTIFIED_NAMELike(String value) {
            addCriterion("SR_REGIONAL_SVI_NOTIFIED_NAME like", value, "SR_REGIONAL_SVI_NOTIFIED_NAME");
            return (Criteria) this;
        }

        public Criteria andSR_REGIONAL_SVI_NOTIFIED_NAMENotLike(String value) {
            addCriterion("SR_REGIONAL_SVI_NOTIFIED_NAME not like", value, "SR_REGIONAL_SVI_NOTIFIED_NAME");
            return (Criteria) this;
        }

        public Criteria andSR_REGIONAL_SVI_NOTIFIED_NAMEIn(List<String> values) {
            addCriterion("SR_REGIONAL_SVI_NOTIFIED_NAME in", values, "SR_REGIONAL_SVI_NOTIFIED_NAME");
            return (Criteria) this;
        }

        public Criteria andSR_REGIONAL_SVI_NOTIFIED_NAMENotIn(List<String> values) {
            addCriterion("SR_REGIONAL_SVI_NOTIFIED_NAME not in", values, "SR_REGIONAL_SVI_NOTIFIED_NAME");
            return (Criteria) this;
        }

        public Criteria andSR_REGIONAL_SVI_NOTIFIED_NAMEBetween(String value1, String value2) {
            addCriterion("SR_REGIONAL_SVI_NOTIFIED_NAME between", value1, value2, "SR_REGIONAL_SVI_NOTIFIED_NAME");
            return (Criteria) this;
        }

        public Criteria andSR_REGIONAL_SVI_NOTIFIED_NAMENotBetween(String value1, String value2) {
            addCriterion("SR_REGIONAL_SVI_NOTIFIED_NAME not between", value1, value2, "SR_REGIONAL_SVI_NOTIFIED_NAME");
            return (Criteria) this;
        }

        public Criteria andSR_VPHIS_SVI_NOTIFIED_NAMEIsNull() {
            addCriterion("SR_VPHIS_SVI_NOTIFIED_NAME is null");
            return (Criteria) this;
        }

        public Criteria andSR_VPHIS_SVI_NOTIFIED_NAMEIsNotNull() {
            addCriterion("SR_VPHIS_SVI_NOTIFIED_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andSR_VPHIS_SVI_NOTIFIED_NAMEEqualTo(String value) {
            addCriterion("SR_VPHIS_SVI_NOTIFIED_NAME =", value, "SR_VPHIS_SVI_NOTIFIED_NAME");
            return (Criteria) this;
        }

        public Criteria andSR_VPHIS_SVI_NOTIFIED_NAMENotEqualTo(String value) {
            addCriterion("SR_VPHIS_SVI_NOTIFIED_NAME <>", value, "SR_VPHIS_SVI_NOTIFIED_NAME");
            return (Criteria) this;
        }

        public Criteria andSR_VPHIS_SVI_NOTIFIED_NAMEGreaterThan(String value) {
            addCriterion("SR_VPHIS_SVI_NOTIFIED_NAME >", value, "SR_VPHIS_SVI_NOTIFIED_NAME");
            return (Criteria) this;
        }

        public Criteria andSR_VPHIS_SVI_NOTIFIED_NAMEGreaterThanOrEqualTo(String value) {
            addCriterion("SR_VPHIS_SVI_NOTIFIED_NAME >=", value, "SR_VPHIS_SVI_NOTIFIED_NAME");
            return (Criteria) this;
        }

        public Criteria andSR_VPHIS_SVI_NOTIFIED_NAMELessThan(String value) {
            addCriterion("SR_VPHIS_SVI_NOTIFIED_NAME <", value, "SR_VPHIS_SVI_NOTIFIED_NAME");
            return (Criteria) this;
        }

        public Criteria andSR_VPHIS_SVI_NOTIFIED_NAMELessThanOrEqualTo(String value) {
            addCriterion("SR_VPHIS_SVI_NOTIFIED_NAME <=", value, "SR_VPHIS_SVI_NOTIFIED_NAME");
            return (Criteria) this;
        }

        public Criteria andSR_VPHIS_SVI_NOTIFIED_NAMELike(String value) {
            addCriterion("SR_VPHIS_SVI_NOTIFIED_NAME like", value, "SR_VPHIS_SVI_NOTIFIED_NAME");
            return (Criteria) this;
        }

        public Criteria andSR_VPHIS_SVI_NOTIFIED_NAMENotLike(String value) {
            addCriterion("SR_VPHIS_SVI_NOTIFIED_NAME not like", value, "SR_VPHIS_SVI_NOTIFIED_NAME");
            return (Criteria) this;
        }

        public Criteria andSR_VPHIS_SVI_NOTIFIED_NAMEIn(List<String> values) {
            addCriterion("SR_VPHIS_SVI_NOTIFIED_NAME in", values, "SR_VPHIS_SVI_NOTIFIED_NAME");
            return (Criteria) this;
        }

        public Criteria andSR_VPHIS_SVI_NOTIFIED_NAMENotIn(List<String> values) {
            addCriterion("SR_VPHIS_SVI_NOTIFIED_NAME not in", values, "SR_VPHIS_SVI_NOTIFIED_NAME");
            return (Criteria) this;
        }

        public Criteria andSR_VPHIS_SVI_NOTIFIED_NAMEBetween(String value1, String value2) {
            addCriterion("SR_VPHIS_SVI_NOTIFIED_NAME between", value1, value2, "SR_VPHIS_SVI_NOTIFIED_NAME");
            return (Criteria) this;
        }

        public Criteria andSR_VPHIS_SVI_NOTIFIED_NAMENotBetween(String value1, String value2) {
            addCriterion("SR_VPHIS_SVI_NOTIFIED_NAME not between", value1, value2, "SR_VPHIS_SVI_NOTIFIED_NAME");
            return (Criteria) this;
        }

        public Criteria andSR_AUDIT_USERIsNull() {
            addCriterion("SR_AUDIT_USER is null");
            return (Criteria) this;
        }

        public Criteria andSR_AUDIT_USERIsNotNull() {
            addCriterion("SR_AUDIT_USER is not null");
            return (Criteria) this;
        }

        public Criteria andSR_AUDIT_USEREqualTo(String value) {
            addCriterion("SR_AUDIT_USER =", value, "SR_AUDIT_USER");
            return (Criteria) this;
        }

        public Criteria andSR_AUDIT_USERNotEqualTo(String value) {
            addCriterion("SR_AUDIT_USER <>", value, "SR_AUDIT_USER");
            return (Criteria) this;
        }

        public Criteria andSR_AUDIT_USERGreaterThan(String value) {
            addCriterion("SR_AUDIT_USER >", value, "SR_AUDIT_USER");
            return (Criteria) this;
        }

        public Criteria andSR_AUDIT_USERGreaterThanOrEqualTo(String value) {
            addCriterion("SR_AUDIT_USER >=", value, "SR_AUDIT_USER");
            return (Criteria) this;
        }

        public Criteria andSR_AUDIT_USERLessThan(String value) {
            addCriterion("SR_AUDIT_USER <", value, "SR_AUDIT_USER");
            return (Criteria) this;
        }

        public Criteria andSR_AUDIT_USERLessThanOrEqualTo(String value) {
            addCriterion("SR_AUDIT_USER <=", value, "SR_AUDIT_USER");
            return (Criteria) this;
        }

        public Criteria andSR_AUDIT_USERLike(String value) {
            addCriterion("SR_AUDIT_USER like", value, "SR_AUDIT_USER");
            return (Criteria) this;
        }

        public Criteria andSR_AUDIT_USERNotLike(String value) {
            addCriterion("SR_AUDIT_USER not like", value, "SR_AUDIT_USER");
            return (Criteria) this;
        }

        public Criteria andSR_AUDIT_USERIn(List<String> values) {
            addCriterion("SR_AUDIT_USER in", values, "SR_AUDIT_USER");
            return (Criteria) this;
        }

        public Criteria andSR_AUDIT_USERNotIn(List<String> values) {
            addCriterion("SR_AUDIT_USER not in", values, "SR_AUDIT_USER");
            return (Criteria) this;
        }

        public Criteria andSR_AUDIT_USERBetween(String value1, String value2) {
            addCriterion("SR_AUDIT_USER between", value1, value2, "SR_AUDIT_USER");
            return (Criteria) this;
        }

        public Criteria andSR_AUDIT_USERNotBetween(String value1, String value2) {
            addCriterion("SR_AUDIT_USER not between", value1, value2, "SR_AUDIT_USER");
            return (Criteria) this;
        }

        public Criteria andSR_AUDIT_DATEIsNull() {
            addCriterion("SR_AUDIT_DATE is null");
            return (Criteria) this;
        }

        public Criteria andSR_AUDIT_DATEIsNotNull() {
            addCriterion("SR_AUDIT_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andSR_AUDIT_DATEEqualTo(Date value) {
            addCriterion("SR_AUDIT_DATE =", value, "SR_AUDIT_DATE");
            return (Criteria) this;
        }

        public Criteria andSR_AUDIT_DATENotEqualTo(Date value) {
            addCriterion("SR_AUDIT_DATE <>", value, "SR_AUDIT_DATE");
            return (Criteria) this;
        }

        public Criteria andSR_AUDIT_DATEGreaterThan(Date value) {
            addCriterion("SR_AUDIT_DATE >", value, "SR_AUDIT_DATE");
            return (Criteria) this;
        }

        public Criteria andSR_AUDIT_DATEGreaterThanOrEqualTo(Date value) {
            addCriterion("SR_AUDIT_DATE >=", value, "SR_AUDIT_DATE");
            return (Criteria) this;
        }

        public Criteria andSR_AUDIT_DATELessThan(Date value) {
            addCriterion("SR_AUDIT_DATE <", value, "SR_AUDIT_DATE");
            return (Criteria) this;
        }

        public Criteria andSR_AUDIT_DATELessThanOrEqualTo(Date value) {
            addCriterion("SR_AUDIT_DATE <=", value, "SR_AUDIT_DATE");
            return (Criteria) this;
        }

        public Criteria andSR_AUDIT_DATEIn(List<Date> values) {
            addCriterion("SR_AUDIT_DATE in", values, "SR_AUDIT_DATE");
            return (Criteria) this;
        }

        public Criteria andSR_AUDIT_DATENotIn(List<Date> values) {
            addCriterion("SR_AUDIT_DATE not in", values, "SR_AUDIT_DATE");
            return (Criteria) this;
        }

        public Criteria andSR_AUDIT_DATEBetween(Date value1, Date value2) {
            addCriterion("SR_AUDIT_DATE between", value1, value2, "SR_AUDIT_DATE");
            return (Criteria) this;
        }

        public Criteria andSR_AUDIT_DATENotBetween(Date value1, Date value2) {
            addCriterion("SR_AUDIT_DATE not between", value1, value2, "SR_AUDIT_DATE");
            return (Criteria) this;
        }

        public Criteria andSR_AUDIT_ACTIONIsNull() {
            addCriterion("SR_AUDIT_ACTION is null");
            return (Criteria) this;
        }

        public Criteria andSR_AUDIT_ACTIONIsNotNull() {
            addCriterion("SR_AUDIT_ACTION is not null");
            return (Criteria) this;
        }

        public Criteria andSR_AUDIT_ACTIONEqualTo(String value) {
            addCriterion("SR_AUDIT_ACTION =", value, "SR_AUDIT_ACTION");
            return (Criteria) this;
        }

        public Criteria andSR_AUDIT_ACTIONNotEqualTo(String value) {
            addCriterion("SR_AUDIT_ACTION <>", value, "SR_AUDIT_ACTION");
            return (Criteria) this;
        }

        public Criteria andSR_AUDIT_ACTIONGreaterThan(String value) {
            addCriterion("SR_AUDIT_ACTION >", value, "SR_AUDIT_ACTION");
            return (Criteria) this;
        }

        public Criteria andSR_AUDIT_ACTIONGreaterThanOrEqualTo(String value) {
            addCriterion("SR_AUDIT_ACTION >=", value, "SR_AUDIT_ACTION");
            return (Criteria) this;
        }

        public Criteria andSR_AUDIT_ACTIONLessThan(String value) {
            addCriterion("SR_AUDIT_ACTION <", value, "SR_AUDIT_ACTION");
            return (Criteria) this;
        }

        public Criteria andSR_AUDIT_ACTIONLessThanOrEqualTo(String value) {
            addCriterion("SR_AUDIT_ACTION <=", value, "SR_AUDIT_ACTION");
            return (Criteria) this;
        }

        public Criteria andSR_AUDIT_ACTIONLike(String value) {
            addCriterion("SR_AUDIT_ACTION like", value, "SR_AUDIT_ACTION");
            return (Criteria) this;
        }

        public Criteria andSR_AUDIT_ACTIONNotLike(String value) {
            addCriterion("SR_AUDIT_ACTION not like", value, "SR_AUDIT_ACTION");
            return (Criteria) this;
        }

        public Criteria andSR_AUDIT_ACTIONIn(List<String> values) {
            addCriterion("SR_AUDIT_ACTION in", values, "SR_AUDIT_ACTION");
            return (Criteria) this;
        }

        public Criteria andSR_AUDIT_ACTIONNotIn(List<String> values) {
            addCriterion("SR_AUDIT_ACTION not in", values, "SR_AUDIT_ACTION");
            return (Criteria) this;
        }

        public Criteria andSR_AUDIT_ACTIONBetween(String value1, String value2) {
            addCriterion("SR_AUDIT_ACTION between", value1, value2, "SR_AUDIT_ACTION");
            return (Criteria) this;
        }

        public Criteria andSR_AUDIT_ACTIONNotBetween(String value1, String value2) {
            addCriterion("SR_AUDIT_ACTION not between", value1, value2, "SR_AUDIT_ACTION");
            return (Criteria) this;
        }

        public Criteria andSR_VER_NUMIsNull() {
            addCriterion("SR_VER_NUM is null");
            return (Criteria) this;
        }

        public Criteria andSR_VER_NUMIsNotNull() {
            addCriterion("SR_VER_NUM is not null");
            return (Criteria) this;
        }

        public Criteria andSR_VER_NUMEqualTo(Short value) {
            addCriterion("SR_VER_NUM =", value, "SR_VER_NUM");
            return (Criteria) this;
        }

        public Criteria andSR_VER_NUMNotEqualTo(Short value) {
            addCriterion("SR_VER_NUM <>", value, "SR_VER_NUM");
            return (Criteria) this;
        }

        public Criteria andSR_VER_NUMGreaterThan(Short value) {
            addCriterion("SR_VER_NUM >", value, "SR_VER_NUM");
            return (Criteria) this;
        }

        public Criteria andSR_VER_NUMGreaterThanOrEqualTo(Short value) {
            addCriterion("SR_VER_NUM >=", value, "SR_VER_NUM");
            return (Criteria) this;
        }

        public Criteria andSR_VER_NUMLessThan(Short value) {
            addCriterion("SR_VER_NUM <", value, "SR_VER_NUM");
            return (Criteria) this;
        }

        public Criteria andSR_VER_NUMLessThanOrEqualTo(Short value) {
            addCriterion("SR_VER_NUM <=", value, "SR_VER_NUM");
            return (Criteria) this;
        }

        public Criteria andSR_VER_NUMIn(List<Short> values) {
            addCriterion("SR_VER_NUM in", values, "SR_VER_NUM");
            return (Criteria) this;
        }

        public Criteria andSR_VER_NUMNotIn(List<Short> values) {
            addCriterion("SR_VER_NUM not in", values, "SR_VER_NUM");
            return (Criteria) this;
        }

        public Criteria andSR_VER_NUMBetween(Short value1, Short value2) {
            addCriterion("SR_VER_NUM between", value1, value2, "SR_VER_NUM");
            return (Criteria) this;
        }

        public Criteria andSR_VER_NUMNotBetween(Short value1, Short value2) {
            addCriterion("SR_VER_NUM not between", value1, value2, "SR_VER_NUM");
            return (Criteria) this;
        }

        public Criteria andSR_AUDIT_CREATE_USERIsNull() {
            addCriterion("SR_AUDIT_CREATE_USER is null");
            return (Criteria) this;
        }

        public Criteria andSR_AUDIT_CREATE_USERIsNotNull() {
            addCriterion("SR_AUDIT_CREATE_USER is not null");
            return (Criteria) this;
        }

        public Criteria andSR_AUDIT_CREATE_USEREqualTo(String value) {
            addCriterion("SR_AUDIT_CREATE_USER =", value, "SR_AUDIT_CREATE_USER");
            return (Criteria) this;
        }

        public Criteria andSR_AUDIT_CREATE_USERNotEqualTo(String value) {
            addCriterion("SR_AUDIT_CREATE_USER <>", value, "SR_AUDIT_CREATE_USER");
            return (Criteria) this;
        }

        public Criteria andSR_AUDIT_CREATE_USERGreaterThan(String value) {
            addCriterion("SR_AUDIT_CREATE_USER >", value, "SR_AUDIT_CREATE_USER");
            return (Criteria) this;
        }

        public Criteria andSR_AUDIT_CREATE_USERGreaterThanOrEqualTo(String value) {
            addCriterion("SR_AUDIT_CREATE_USER >=", value, "SR_AUDIT_CREATE_USER");
            return (Criteria) this;
        }

        public Criteria andSR_AUDIT_CREATE_USERLessThan(String value) {
            addCriterion("SR_AUDIT_CREATE_USER <", value, "SR_AUDIT_CREATE_USER");
            return (Criteria) this;
        }

        public Criteria andSR_AUDIT_CREATE_USERLessThanOrEqualTo(String value) {
            addCriterion("SR_AUDIT_CREATE_USER <=", value, "SR_AUDIT_CREATE_USER");
            return (Criteria) this;
        }

        public Criteria andSR_AUDIT_CREATE_USERLike(String value) {
            addCriterion("SR_AUDIT_CREATE_USER like", value, "SR_AUDIT_CREATE_USER");
            return (Criteria) this;
        }

        public Criteria andSR_AUDIT_CREATE_USERNotLike(String value) {
            addCriterion("SR_AUDIT_CREATE_USER not like", value, "SR_AUDIT_CREATE_USER");
            return (Criteria) this;
        }

        public Criteria andSR_AUDIT_CREATE_USERIn(List<String> values) {
            addCriterion("SR_AUDIT_CREATE_USER in", values, "SR_AUDIT_CREATE_USER");
            return (Criteria) this;
        }

        public Criteria andSR_AUDIT_CREATE_USERNotIn(List<String> values) {
            addCriterion("SR_AUDIT_CREATE_USER not in", values, "SR_AUDIT_CREATE_USER");
            return (Criteria) this;
        }

        public Criteria andSR_AUDIT_CREATE_USERBetween(String value1, String value2) {
            addCriterion("SR_AUDIT_CREATE_USER between", value1, value2, "SR_AUDIT_CREATE_USER");
            return (Criteria) this;
        }

        public Criteria andSR_AUDIT_CREATE_USERNotBetween(String value1, String value2) {
            addCriterion("SR_AUDIT_CREATE_USER not between", value1, value2, "SR_AUDIT_CREATE_USER");
            return (Criteria) this;
        }

        public Criteria andSR_AUDIT_CREATE_DATEIsNull() {
            addCriterion("SR_AUDIT_CREATE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andSR_AUDIT_CREATE_DATEIsNotNull() {
            addCriterion("SR_AUDIT_CREATE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andSR_AUDIT_CREATE_DATEEqualTo(Date value) {
            addCriterion("SR_AUDIT_CREATE_DATE =", value, "SR_AUDIT_CREATE_DATE");
            return (Criteria) this;
        }

        public Criteria andSR_AUDIT_CREATE_DATENotEqualTo(Date value) {
            addCriterion("SR_AUDIT_CREATE_DATE <>", value, "SR_AUDIT_CREATE_DATE");
            return (Criteria) this;
        }

        public Criteria andSR_AUDIT_CREATE_DATEGreaterThan(Date value) {
            addCriterion("SR_AUDIT_CREATE_DATE >", value, "SR_AUDIT_CREATE_DATE");
            return (Criteria) this;
        }

        public Criteria andSR_AUDIT_CREATE_DATEGreaterThanOrEqualTo(Date value) {
            addCriterion("SR_AUDIT_CREATE_DATE >=", value, "SR_AUDIT_CREATE_DATE");
            return (Criteria) this;
        }

        public Criteria andSR_AUDIT_CREATE_DATELessThan(Date value) {
            addCriterion("SR_AUDIT_CREATE_DATE <", value, "SR_AUDIT_CREATE_DATE");
            return (Criteria) this;
        }

        public Criteria andSR_AUDIT_CREATE_DATELessThanOrEqualTo(Date value) {
            addCriterion("SR_AUDIT_CREATE_DATE <=", value, "SR_AUDIT_CREATE_DATE");
            return (Criteria) this;
        }

        public Criteria andSR_AUDIT_CREATE_DATEIn(List<Date> values) {
            addCriterion("SR_AUDIT_CREATE_DATE in", values, "SR_AUDIT_CREATE_DATE");
            return (Criteria) this;
        }

        public Criteria andSR_AUDIT_CREATE_DATENotIn(List<Date> values) {
            addCriterion("SR_AUDIT_CREATE_DATE not in", values, "SR_AUDIT_CREATE_DATE");
            return (Criteria) this;
        }

        public Criteria andSR_AUDIT_CREATE_DATEBetween(Date value1, Date value2) {
            addCriterion("SR_AUDIT_CREATE_DATE between", value1, value2, "SR_AUDIT_CREATE_DATE");
            return (Criteria) this;
        }

        public Criteria andSR_AUDIT_CREATE_DATENotBetween(Date value1, Date value2) {
            addCriterion("SR_AUDIT_CREATE_DATE not between", value1, value2, "SR_AUDIT_CREATE_DATE");
            return (Criteria) this;
        }

        public Criteria andSR_AUDIT_LOCATIONIsNull() {
            addCriterion("SR_AUDIT_LOCATION is null");
            return (Criteria) this;
        }

        public Criteria andSR_AUDIT_LOCATIONIsNotNull() {
            addCriterion("SR_AUDIT_LOCATION is not null");
            return (Criteria) this;
        }

        public Criteria andSR_AUDIT_LOCATIONEqualTo(String value) {
            addCriterion("SR_AUDIT_LOCATION =", value, "SR_AUDIT_LOCATION");
            return (Criteria) this;
        }

        public Criteria andSR_AUDIT_LOCATIONNotEqualTo(String value) {
            addCriterion("SR_AUDIT_LOCATION <>", value, "SR_AUDIT_LOCATION");
            return (Criteria) this;
        }

        public Criteria andSR_AUDIT_LOCATIONGreaterThan(String value) {
            addCriterion("SR_AUDIT_LOCATION >", value, "SR_AUDIT_LOCATION");
            return (Criteria) this;
        }

        public Criteria andSR_AUDIT_LOCATIONGreaterThanOrEqualTo(String value) {
            addCriterion("SR_AUDIT_LOCATION >=", value, "SR_AUDIT_LOCATION");
            return (Criteria) this;
        }

        public Criteria andSR_AUDIT_LOCATIONLessThan(String value) {
            addCriterion("SR_AUDIT_LOCATION <", value, "SR_AUDIT_LOCATION");
            return (Criteria) this;
        }

        public Criteria andSR_AUDIT_LOCATIONLessThanOrEqualTo(String value) {
            addCriterion("SR_AUDIT_LOCATION <=", value, "SR_AUDIT_LOCATION");
            return (Criteria) this;
        }

        public Criteria andSR_AUDIT_LOCATIONLike(String value) {
            addCriterion("SR_AUDIT_LOCATION like", value, "SR_AUDIT_LOCATION");
            return (Criteria) this;
        }

        public Criteria andSR_AUDIT_LOCATIONNotLike(String value) {
            addCriterion("SR_AUDIT_LOCATION not like", value, "SR_AUDIT_LOCATION");
            return (Criteria) this;
        }

        public Criteria andSR_AUDIT_LOCATIONIn(List<String> values) {
            addCriterion("SR_AUDIT_LOCATION in", values, "SR_AUDIT_LOCATION");
            return (Criteria) this;
        }

        public Criteria andSR_AUDIT_LOCATIONNotIn(List<String> values) {
            addCriterion("SR_AUDIT_LOCATION not in", values, "SR_AUDIT_LOCATION");
            return (Criteria) this;
        }

        public Criteria andSR_AUDIT_LOCATIONBetween(String value1, String value2) {
            addCriterion("SR_AUDIT_LOCATION between", value1, value2, "SR_AUDIT_LOCATION");
            return (Criteria) this;
        }

        public Criteria andSR_AUDIT_LOCATIONNotBetween(String value1, String value2) {
            addCriterion("SR_AUDIT_LOCATION not between", value1, value2, "SR_AUDIT_LOCATION");
            return (Criteria) this;
        }

        public Criteria andSR_PREM_IDIsNull() {
            addCriterion("SR_PREM_ID is null");
            return (Criteria) this;
        }

        public Criteria andSR_PREM_IDIsNotNull() {
            addCriterion("SR_PREM_ID is not null");
            return (Criteria) this;
        }

        public Criteria andSR_PREM_IDEqualTo(Short value) {
            addCriterion("SR_PREM_ID =", value, "SR_PREM_ID");
            return (Criteria) this;
        }

        public Criteria andSR_PREM_IDNotEqualTo(Short value) {
            addCriterion("SR_PREM_ID <>", value, "SR_PREM_ID");
            return (Criteria) this;
        }

        public Criteria andSR_PREM_IDGreaterThan(Short value) {
            addCriterion("SR_PREM_ID >", value, "SR_PREM_ID");
            return (Criteria) this;
        }

        public Criteria andSR_PREM_IDGreaterThanOrEqualTo(Short value) {
            addCriterion("SR_PREM_ID >=", value, "SR_PREM_ID");
            return (Criteria) this;
        }

        public Criteria andSR_PREM_IDLessThan(Short value) {
            addCriterion("SR_PREM_ID <", value, "SR_PREM_ID");
            return (Criteria) this;
        }

        public Criteria andSR_PREM_IDLessThanOrEqualTo(Short value) {
            addCriterion("SR_PREM_ID <=", value, "SR_PREM_ID");
            return (Criteria) this;
        }

        public Criteria andSR_PREM_IDIn(List<Short> values) {
            addCriterion("SR_PREM_ID in", values, "SR_PREM_ID");
            return (Criteria) this;
        }

        public Criteria andSR_PREM_IDNotIn(List<Short> values) {
            addCriterion("SR_PREM_ID not in", values, "SR_PREM_ID");
            return (Criteria) this;
        }

        public Criteria andSR_PREM_IDBetween(Short value1, Short value2) {
            addCriterion("SR_PREM_ID between", value1, value2, "SR_PREM_ID");
            return (Criteria) this;
        }

        public Criteria andSR_PREM_IDNotBetween(Short value1, Short value2) {
            addCriterion("SR_PREM_ID not between", value1, value2, "SR_PREM_ID");
            return (Criteria) this;
        }

        public Criteria andSR_JPA_UPDATED_BYIsNull() {
            addCriterion("SR_JPA_UPDATED_BY is null");
            return (Criteria) this;
        }

        public Criteria andSR_JPA_UPDATED_BYIsNotNull() {
            addCriterion("SR_JPA_UPDATED_BY is not null");
            return (Criteria) this;
        }

        public Criteria andSR_JPA_UPDATED_BYEqualTo(String value) {
            addCriterion("SR_JPA_UPDATED_BY =", value, "SR_JPA_UPDATED_BY");
            return (Criteria) this;
        }

        public Criteria andSR_JPA_UPDATED_BYNotEqualTo(String value) {
            addCriterion("SR_JPA_UPDATED_BY <>", value, "SR_JPA_UPDATED_BY");
            return (Criteria) this;
        }

        public Criteria andSR_JPA_UPDATED_BYGreaterThan(String value) {
            addCriterion("SR_JPA_UPDATED_BY >", value, "SR_JPA_UPDATED_BY");
            return (Criteria) this;
        }

        public Criteria andSR_JPA_UPDATED_BYGreaterThanOrEqualTo(String value) {
            addCriterion("SR_JPA_UPDATED_BY >=", value, "SR_JPA_UPDATED_BY");
            return (Criteria) this;
        }

        public Criteria andSR_JPA_UPDATED_BYLessThan(String value) {
            addCriterion("SR_JPA_UPDATED_BY <", value, "SR_JPA_UPDATED_BY");
            return (Criteria) this;
        }

        public Criteria andSR_JPA_UPDATED_BYLessThanOrEqualTo(String value) {
            addCriterion("SR_JPA_UPDATED_BY <=", value, "SR_JPA_UPDATED_BY");
            return (Criteria) this;
        }

        public Criteria andSR_JPA_UPDATED_BYLike(String value) {
            addCriterion("SR_JPA_UPDATED_BY like", value, "SR_JPA_UPDATED_BY");
            return (Criteria) this;
        }

        public Criteria andSR_JPA_UPDATED_BYNotLike(String value) {
            addCriterion("SR_JPA_UPDATED_BY not like", value, "SR_JPA_UPDATED_BY");
            return (Criteria) this;
        }

        public Criteria andSR_JPA_UPDATED_BYIn(List<String> values) {
            addCriterion("SR_JPA_UPDATED_BY in", values, "SR_JPA_UPDATED_BY");
            return (Criteria) this;
        }

        public Criteria andSR_JPA_UPDATED_BYNotIn(List<String> values) {
            addCriterion("SR_JPA_UPDATED_BY not in", values, "SR_JPA_UPDATED_BY");
            return (Criteria) this;
        }

        public Criteria andSR_JPA_UPDATED_BYBetween(String value1, String value2) {
            addCriterion("SR_JPA_UPDATED_BY between", value1, value2, "SR_JPA_UPDATED_BY");
            return (Criteria) this;
        }

        public Criteria andSR_JPA_UPDATED_BYNotBetween(String value1, String value2) {
            addCriterion("SR_JPA_UPDATED_BY not between", value1, value2, "SR_JPA_UPDATED_BY");
            return (Criteria) this;
        }

        public Criteria andSR_JPA_UPDATED_DATEIsNull() {
            addCriterion("SR_JPA_UPDATED_DATE is null");
            return (Criteria) this;
        }

        public Criteria andSR_JPA_UPDATED_DATEIsNotNull() {
            addCriterion("SR_JPA_UPDATED_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andSR_JPA_UPDATED_DATEEqualTo(Date value) {
            addCriterion("SR_JPA_UPDATED_DATE =", value, "SR_JPA_UPDATED_DATE");
            return (Criteria) this;
        }

        public Criteria andSR_JPA_UPDATED_DATENotEqualTo(Date value) {
            addCriterion("SR_JPA_UPDATED_DATE <>", value, "SR_JPA_UPDATED_DATE");
            return (Criteria) this;
        }

        public Criteria andSR_JPA_UPDATED_DATEGreaterThan(Date value) {
            addCriterion("SR_JPA_UPDATED_DATE >", value, "SR_JPA_UPDATED_DATE");
            return (Criteria) this;
        }

        public Criteria andSR_JPA_UPDATED_DATEGreaterThanOrEqualTo(Date value) {
            addCriterion("SR_JPA_UPDATED_DATE >=", value, "SR_JPA_UPDATED_DATE");
            return (Criteria) this;
        }

        public Criteria andSR_JPA_UPDATED_DATELessThan(Date value) {
            addCriterion("SR_JPA_UPDATED_DATE <", value, "SR_JPA_UPDATED_DATE");
            return (Criteria) this;
        }

        public Criteria andSR_JPA_UPDATED_DATELessThanOrEqualTo(Date value) {
            addCriterion("SR_JPA_UPDATED_DATE <=", value, "SR_JPA_UPDATED_DATE");
            return (Criteria) this;
        }

        public Criteria andSR_JPA_UPDATED_DATEIn(List<Date> values) {
            addCriterion("SR_JPA_UPDATED_DATE in", values, "SR_JPA_UPDATED_DATE");
            return (Criteria) this;
        }

        public Criteria andSR_JPA_UPDATED_DATENotIn(List<Date> values) {
            addCriterion("SR_JPA_UPDATED_DATE not in", values, "SR_JPA_UPDATED_DATE");
            return (Criteria) this;
        }

        public Criteria andSR_JPA_UPDATED_DATEBetween(Date value1, Date value2) {
            addCriterion("SR_JPA_UPDATED_DATE between", value1, value2, "SR_JPA_UPDATED_DATE");
            return (Criteria) this;
        }

        public Criteria andSR_JPA_UPDATED_DATENotBetween(Date value1, Date value2) {
            addCriterion("SR_JPA_UPDATED_DATE not between", value1, value2, "SR_JPA_UPDATED_DATE");
            return (Criteria) this;
        }

        public Criteria andSR_JPA_VERSIONIsNull() {
            addCriterion("SR_JPA_VERSION is null");
            return (Criteria) this;
        }

        public Criteria andSR_JPA_VERSIONIsNotNull() {
            addCriterion("SR_JPA_VERSION is not null");
            return (Criteria) this;
        }

        public Criteria andSR_JPA_VERSIONEqualTo(Short value) {
            addCriterion("SR_JPA_VERSION =", value, "SR_JPA_VERSION");
            return (Criteria) this;
        }

        public Criteria andSR_JPA_VERSIONNotEqualTo(Short value) {
            addCriterion("SR_JPA_VERSION <>", value, "SR_JPA_VERSION");
            return (Criteria) this;
        }

        public Criteria andSR_JPA_VERSIONGreaterThan(Short value) {
            addCriterion("SR_JPA_VERSION >", value, "SR_JPA_VERSION");
            return (Criteria) this;
        }

        public Criteria andSR_JPA_VERSIONGreaterThanOrEqualTo(Short value) {
            addCriterion("SR_JPA_VERSION >=", value, "SR_JPA_VERSION");
            return (Criteria) this;
        }

        public Criteria andSR_JPA_VERSIONLessThan(Short value) {
            addCriterion("SR_JPA_VERSION <", value, "SR_JPA_VERSION");
            return (Criteria) this;
        }

        public Criteria andSR_JPA_VERSIONLessThanOrEqualTo(Short value) {
            addCriterion("SR_JPA_VERSION <=", value, "SR_JPA_VERSION");
            return (Criteria) this;
        }

        public Criteria andSR_JPA_VERSIONIn(List<Short> values) {
            addCriterion("SR_JPA_VERSION in", values, "SR_JPA_VERSION");
            return (Criteria) this;
        }

        public Criteria andSR_JPA_VERSIONNotIn(List<Short> values) {
            addCriterion("SR_JPA_VERSION not in", values, "SR_JPA_VERSION");
            return (Criteria) this;
        }

        public Criteria andSR_JPA_VERSIONBetween(Short value1, Short value2) {
            addCriterion("SR_JPA_VERSION between", value1, value2, "SR_JPA_VERSION");
            return (Criteria) this;
        }

        public Criteria andSR_JPA_VERSIONNotBetween(Short value1, Short value2) {
            addCriterion("SR_JPA_VERSION not between", value1, value2, "SR_JPA_VERSION");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TDED_SUSPECT_REPORTS
     *
     * @mbg.generated do_not_delete_during_merge Tue Dec 15 16:02:14 GMT 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TDED_SUSPECT_REPORTS
     *
     * @mbg.generated Tue Dec 15 16:02:14 GMT 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}