package com.expleoautomation.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface TDED_SUSPECT_REPORTSMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TDED_SUSPECT_REPORTS
     *
     * @mbg.generated Tue Dec 15 16:02:14 GMT 2020
     */
    long countByExample(TDED_SUSPECT_REPORTSExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TDED_SUSPECT_REPORTS
     *
     * @mbg.generated Tue Dec 15 16:02:14 GMT 2020
     */
    int deleteByExample(TDED_SUSPECT_REPORTSExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TDED_SUSPECT_REPORTS
     *
     * @mbg.generated Tue Dec 15 16:02:14 GMT 2020
     */
    int deleteByPrimaryKey(Short SR_ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TDED_SUSPECT_REPORTS
     *
     * @mbg.generated Tue Dec 15 16:02:14 GMT 2020
     */
    int insert(TDED_SUSPECT_REPORTS record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TDED_SUSPECT_REPORTS
     *
     * @mbg.generated Tue Dec 15 16:02:14 GMT 2020
     */
    int insertSelective(TDED_SUSPECT_REPORTS record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TDED_SUSPECT_REPORTS
     *
     * @mbg.generated Tue Dec 15 16:02:14 GMT 2020
     */
    List<TDED_SUSPECT_REPORTS> selectByExample(TDED_SUSPECT_REPORTSExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TDED_SUSPECT_REPORTS
     *
     * @mbg.generated Tue Dec 15 16:02:14 GMT 2020
     */
    TDED_SUSPECT_REPORTS selectByPrimaryKey(Short SR_ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TDED_SUSPECT_REPORTS
     *
     * @mbg.generated Tue Dec 15 16:02:14 GMT 2020
     */
    int updateByExampleSelective(@Param("record") TDED_SUSPECT_REPORTS record, @Param("example") TDED_SUSPECT_REPORTSExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TDED_SUSPECT_REPORTS
     *
     * @mbg.generated Tue Dec 15 16:02:14 GMT 2020
     */
    int updateByExample(@Param("record") TDED_SUSPECT_REPORTS record, @Param("example") TDED_SUSPECT_REPORTSExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TDED_SUSPECT_REPORTS
     *
     * @mbg.generated Tue Dec 15 16:02:14 GMT 2020
     */
    int updateByPrimaryKeySelective(TDED_SUSPECT_REPORTS record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TDED_SUSPECT_REPORTS
     *
     * @mbg.generated Tue Dec 15 16:02:14 GMT 2020
     */
    int updateByPrimaryKey(TDED_SUSPECT_REPORTS record);
}